"""empty message"""

revision = 'dbc2eba828d0'
down_revision = 'de2842012ef5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    """Apply the migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OAuthAccount',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('github', 'no_provider', name='oauth_providers_enum'), server_default='no_provider', nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_login', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_oauth_user_provider')
    )
    op.create_index(op.f('ix_OAuthAccount_provider_user_id'), 'OAuthAccount', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_OAuthAccount_user_id'), 'OAuthAccount', ['user_id'], unique=False)
    op.alter_column('user', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_OAuthAccount_user_id'), table_name='OAuthAccount')
    op.drop_index(op.f('ix_OAuthAccount_provider_user_id'), table_name='OAuthAccount')
    op.drop_table('OAuthAccount')
    # ### end Alembic commands ###
